### PR TITLE
feat: add custom struct type matching to `Register` via `structTypeMatches`

### PR DESCRIPTION
**Pull request by architect-dev**
This PR allows users and library authors to inject custom types that match their custom solidity structs. The use case is narrow, but allows library authors to create more expressive tools that interact with viem and wagmi. I have created a discussion that this PR references: https://github.com/wevm/abitype/discussions/250

I've added a new test in `register.test-d.ts` which unfortunately can only be run locally since it relies on declaration merging to test. Hopefully the test shows the kind of problem I'm trying to solve with this PR, which is that without the `internalType` it is impossible to differentiate between structs with different names but matching types after the ABI has been broken down into primitives. 

This PR is somewhat outside the scope of what `abitype` is, so I can understand if this isn't something you would like to add to the project, however it is useful for me and may be useful for others, so I've opened the PR in case that is true.

Thanks for taking a look!

---

## PR-Codex overview
This PR introduces `structTypeMatches` to `Register` in `abitype`, allowing custom struct types to be matched against structs before processing. 

### Detailed summary
- Added `structTypeMatches` to `Register` in `abitype`
- Defined `ResolvedStructMatchesMap` and `ResolvedStructMatchesUnion`
- Updated `AbiParameterToPrimitiveType` in `utils.ts` to handle user-defined struct matches

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by tmm** [comment]
Thanks for the discussion and PR! Haven't had a chance to review or consider this yet, but figured I would provide some quick comments.

> The use case is narrow, but allows library authors to create more expressive tools that interact with viem and wagmi.

What's an example of how this would look in Viem/Wagmi?

> I've added a new test in register.test-d.ts which unfortunately can only be run locally since it relies on declaration merging to test.

You should be able to add the register tests in [`packages/register-tests/default/src`](https://github.com/wevm/abitype/blob/main/packages/register-tests/default/src).

**Comment by architect-dev** [comment]
It would allow typings like this when integrated with wagmi hooks:

CleanShot 2024-08-28 at 20 11 07@2x

In this particular case, all of the EncryptedXXXX share the same type, but need to be encrypted differently in order to be handled appropriately by the contract. By hooking into the struct name I can assign a custom type for each that I can discriminate with and improve other engineers typesafety.

As an example, I can imagine a contract where a user is dealing with shapes, and creates something like `struct Box {uint8 x, uint8 y, uint8 w, uint8 h}` in their contract. A function like `addBox(ShapeBox calldata box)` would end up in the viem/wagmi args as `[{ x: number, y: number, w: number, h: number} | undefined]`, but they could use this feature and set the `ShapeBox` struct in the Register to a typescript `Box` type. As a result, in viem/wagmi the args of `addBox` would be `[Box | undefined]`. This use case only improves readability, but it might help explain where I see it having value.

Thanks for the tip on the `register-tests` I missed that one, I'll add a test in there tomorrow!

**Review by OKEAMAH — APPROVED** [review]
Good

**Comment by tmm** [comment]
Closing this for now. Going to think about for ABIType v2.

**Pull request closed without merging**
